### PR TITLE
fix bug import discussions without replies

### PR DESCRIPTION
**Pull request by dshovchko**

### CODE REVIEW

**Comment by MichaelBelgium** [comment]
Why +1?
Also lastpostnumber is **not** the count, its the number of the post and that always starts at 1

**Comment by dshovchko** [comment]
then I will offer this variant

**Comment by MichaelBelgium** [comment]
After some digging I agree there's an issue with comment count but the problem isn't in the database ...

For example if you look at [this mybb post](http://lmdm.exp-gaming.net/mybb/showthread.php?tid=130) and this is in the mybb db:
mybb db
(http://puu.sh/vCdam.png)

It does have 3 replies. And it does have also in flarum:
flarum db
(http://puu.sh/vCdg5.png)

But in flarum it says 2 in the thread overview: flarum toverview
(http://puu.sh/vCdhU.png)

while in mybb it does say 3: mybb toverview
(http://puu.sh/vCdjy.png)

**Comment by dshovchko** [comment]
I have selected 3 discussions converted from mybb:
id 1 has 0 replies
id 11 has 1 reply
id 121 has 2 replies

And created in flarum 3 discussions:
id 131 has 0 replies
id 132 has 1 reply
id 133 has 2 replies

**Comment by dshovchko** [comment]
I have made it

**Comment by MichaelBelgium** [comment]
What does it say in the mybb database ? Id 1, 11 and 12 - replies

**Comment by dshovchko** [comment]
https://ibb.co/gjwk0k

**Comment by dshovchko** [comment]
I have added ORDER BY in query and changed setting comments_count and last_post_number

**Comment by MichaelBelgium** [comment]
Ok, I get the comments_count now, its not logical tho, but i'll commit/fix it myself as i added some stuff already

**Comment by dshovchko** [comment]
Ок

**Pull request closed without merging**
