### PR TITLE
add the hierarchy of tags

### PR DESCRIPTION
**Pull request by dshovchko**
Automatic addition of the discussion in the parent tag (well as this makes the flarum)

### CODE REVIEW

**Comment by dshovchko** [comment]
I don't know what could be wrong? After importing from mybb are not visible discussions in which only one message (without comments). And the administrators are see their, but others users and guests aren't.

**Comment by MichaelBelgium** [comment]
You talking about soft deleted threads?

**Comment by dshovchko** [comment]
so it was in mybb - https://ibb.co/joxAgQ
guest sees the forum so - https://ibb.co/i8uO1Q
admin sees the forum so - https://ibb.co/bw3GMQ

As you can see, there are no topics with 0 replies.

**Comment by dshovchko** [comment]
> You talking about soft deleted threads?

No

**Comment by dshovchko** [comment]
> nvm fixed it

Good!

**Comment by MichaelBelgium** [comment]
Hmm thats strange! I would say its about flarum permissions or some kind

**Comment by MichaelBelgium** [comment]
@dshovchko Can u try to add
```PHP
$configurator->BBCodes->addCustom('[size={CHOICE=large,small,xx-small,x-small,medium,x-large,xx-large}]{TEXT}[/size]','<span style="font-size: {CHOICE}">{TEXT}</span>');```

to your config file to support the MyBB size bbcode? And tell me if it works or not?

If i add this line i'm getting `font-size: xx-largepx;` in the css/forum

**Comment by dshovchko** [comment]
It doesn't work.

`preg_replace('/\[size=(large|small|xx-small|x-small|medium|x-large|xx-large)\](.+?)\[\/size\]/iu', '<span style="font-size: $1">$2</span>', $row["message"]);`
works better

**Pull request merged**
