### PR TITLE
Slight improvements

### PR DESCRIPTION
**Pull request by dshovchko**
1. correct work with Cyrillic
2. increase max execution time for script

### CODE REVIEW

**Comment by MichaelBelgium** [comment]
Useful improvements but while using the time limit, isnt it better to set it 0?

**Comment by dshovchko** [comment]
Really, somehow did not think about it. I have corrected

**Comment by MichaelBelgium** [comment]
@dshovchko Maybe changing to UTF8 wasn't a good idea, truncating tables are not working anymore. Unless u can fix it, feel free to commit again.

 `Cannot truncate a table referenced in a foreign key constraint (`flar_recipients`, CONSTRAINT `recipients_discussion_id_foreign` FOREIGN KEY (`discussion_id`) REFERENCES .`flar_discussions` (`id`))`

**Comment by dshovchko** [comment]
It's strange. It works for me perfectly.

I think, it's not because of UTF8. Try to clear the base and perform migration again.

PS. Perhaps, you didn't truncate all necessary tables.

**Comment by dshovchko** [comment]
In my DB isn't such table "recipients"!

**Comment by MichaelBelgium** [comment]
Ah! Yeah indeed, I wanted to test and installed this private discussions extension, that created this table. In case i could migrate private messages into these private discussions.

**Pull request merged**
